# the file 2l-small.xyz was generated by gen_pts.py
./compilation

./launch_calc.sh 2l-small.xyz output-l2-small/ 0 601
./bottleneckify.py output-l2-small output-l2-small/599.pers > l2-small-bottleneck.dist
cat 2l-small.xyz | ./ptdist.py 599