# Describe the pipeline

# the file 2l-small.xyz was generated by gen_pts.py
./compilation

./launch_calc.sh 2l-small-width.xyz output-2l-small-width/ 0 601
./bottleneckify.py output-2l-small-width output-2l-small-width/599.pers > l2-small-width-bottleneck.dist
cat 2l-small-width.xyz | ./ptdist.py 599
