#!/usr/bin/python
# Compute graph data
#
# usage : ./auto.sh filename.xyz

#Nb :
# the file 2l-small.xyz was generated by gen_pts.py
# You can compile rips-zz with
#./compilation

import matplotlib.pyplot as plt
import sys
import fileinput
import os.path
import math
import numpy as np
import subprocess

if len(sys.argv) < 2:
  print("usage: xyz_file")
  exit(0)

xyz = sys.argv[1]
name = os.path.splitext(os.path.basename(xyz))[0]

#read xyz
pt = []
for line in open(xyz):
  (x, y, z) = line.split()
  pt.append((float(x), float(y), float(z)))

try:
  os.mkdir('output-' + name + '/')
except OSError:
  pass

subprocess.call(['./launch_calc.sh',
                 xyz,
                 'output-' + name + '/',
                 '0',
                 str(len(xyz) - 1)])
print './bottleneckify.py output-'+name+' output-'+name+'/0.pers > '+name+'-bottleneck.dist'
subprocess.call(['sh', '-c',  './bottleneckify.py output-'+name+' output-'+name+'/0.pers > '+name+'-bottleneck.dist'])

# to draw :
subprocess.call(['./draw_ptdist_bottleneck.py', xyz, '0', name+'-bottleneck.dist'])
